import dgram from 'node:dgram';import fs from 'node:fs';import {ROOT,read,write} from './unify.mjs';import path from 'node:path';
const args=process.argv.slice(2),arg=(n,d)=>{const i=args.indexOf('--'+n);return i<0?d:args[i+1];},port=Number(arg('port','5398')),seconds=Number(arg('seconds','100')),loop=args.includes('--loop'),url='http://127.0.0.1:8789';
if(![5398,5399].includes(port)||seconds<5||seconds>3600)throw Error('Demo only 5398/5399, seconds 5..3600');
const {route}=read('data/demo_route.json'),lengths=[0];for(let i=1;i<route.length;i++)lengths.push(lengths.at(-1)+Math.hypot(route[i][0]-route[i-1][0],route[i][1]-route[i-1][1]));const total=lengths.at(-1),socket=dgram.createSocket('udp4');
await fetch(url+'/api/demo/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:true})});
const start=performance.now();let count=0,last=null;const samples=[];
function finish(){clearInterval(timer);if(last)socket.send(Buffer.from(JSON.stringify({...last,lost:true,moving:false,ts_ms:Date.now(),demo:true})),port,'127.0.0.1',()=>socket.close());else socket.close();write('out/demo_stream.json',{port,hz:10,count,started_at:new Date(Date.now()-(performance.now()-start)).toISOString(),elapsed_s:(performance.now()-start)/1000,samples,commands_sent:0});fetch(url+'/api/demo/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:false})}).catch(()=>{});}
let exiting=false;const timer=setInterval(()=>{const elapsed=(performance.now()-start)/1000;if(elapsed>=seconds&&!loop){if(!exiting){exiting=true;finish();}return;}const phase=(elapsed%60)/60,dist=phase*total;let i=1;while(i<lengths.length-1&&lengths[i]<dist)i++;const t=(dist-lengths[i-1])/(lengths[i]-lengths[i-1]||1),a=route[i-1],b=route[i];last={x_m:a[0]+(b[0]-a[0])*t,y_m:a[1]+(b[1]-a[1])*t,yaw_rad:Math.atan2(b[1]-a[1],b[0]-a[0]),lost:false,moving:true,ts_ms:Date.now(),demo:true};socket.send(Buffer.from(JSON.stringify(last)),port,'127.0.0.1');if(count%10===0)samples.push(last);count++;},100);
process.on('SIGINT',()=>{if(!exiting){exiting=true;finish();}});console.log(`DEMO S0 → B → A @ 10Hz UDP ${port}; physical commands=0`);
