import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {ROOT,read,write,mapData,revision} from './unify.mjs';
import {routeCollisions,footprints,overlaps,robotPolygon,routeSamples} from './realism-geometry.mjs';
import {createMotion,gaitFeet,legPose} from '../web/robot-motion.mjs';
import {createPoseStore} from './pose-state.mjs';
import {runDemo} from './demo-http.mjs';

const checks=[],check=(name,fn)=>{fn();checks.push({name,passed:true});},scene=read('data/scene.json'),before=read('out/scene_before_T.json'),report=read('out/realism.json');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const originalRoot=path.dirname(ROOT),originalFiles=['server.mjs','web/main.js','web/presentation.js','web/robot-link.js','src/demo-poses.mjs','data/scene.json','data/baseline.json'];
const originalHashes=originalFiles.map(name=>({name,sha256:hash(path.join(originalRoot,name))}));
check('13 user-edited objects preserved in full',()=>{assert.equal(scene.realism.protected_ids.length,13);for(const id of scene.realism.protected_ids)assert.deepEqual(scene.objects.find(o=>o.id===id),before.objects.find(o=>o.id===id));});
check('original live scene snapshot still current',()=>{assert.deepEqual(JSON.parse(fs.readFileSync(path.join(originalRoot,'data/scene.json'),'utf8')),before);});
check('all navigation and localization bundle bytes unchanged',()=>{for(const p of report.map_hashes){assert.equal(hash(path.join(ROOT,'data/map',p.name)),p.sha256);assert.equal(hash(path.join(originalRoot,'data/map',p.name)),p.sha256);}});
check('removed storage retained for undo; canonical and USD revisions agree',()=>{assert.equal(scene.objects.find(o=>o.id==='passage_storage_boxes').visible,false);assert.equal(revision(scene),scene.revision);assert.equal(read('exports/manifest.json').revision,scene.revision);const usd=fs.readFileSync(path.join(ROOT,'exports/house_sim.usda'),'utf8');assert(usd.includes('def Xform "passage_storage_boxes"'));assert(usd.split('def Xform "passage_storage_boxes"')[1].includes('token visibility = "invisible"'));});
const collisions=routeCollisions(scene);
report.after=collisions;write('out/realism.json',report);
check('S0–B–A route has zero canonical or LOD furniture intersections',()=>assert.deepEqual(collisions.hits,[]));
check('drawer shrink retains rear face and introduces no furniture penetration',()=>{const o=scene.objects.find(o=>o.id==='living_drawers'),old=before.objects.find(p=>p.id===o.id);assert.deepEqual(o.position,old.position);const min=o=>Math.min(...o.parts.flatMap(p=>p.vertices.map(v=>v[0])));assert.equal(min(o),min(old));for(const other of scene.objects.filter(p=>p.visible&&p.category==='furniture'&&p.id!==o.id))assert(!footprints(o).some(a=>footprints(other).some(b=>overlaps(a.polygon,b.polygon))),other.id);});
check('above-height top excluded, independent desk legs kept',()=>{const o={yaw:0,position:[0,0,0],parts:[{name:'top',vertices:[[-1,-1,.7],[1,-1,.7],[1,1,.75],[-1,1,.75]],triangles:[[0,1,2],[0,2,3]]}]};assert.equal(footprints(o).length,0);assert(footprints(scene.objects.find(o=>o.id==='living_desk')).length>=4);});
const m=mapData(),route=read('data/demo_route.json').route;
check('route remains on authoritative free cells; frame round trip',()=>{for(const p of route){const xy=m.toMap(...p),x=Math.floor((xy[0]-m.meta.origin_x)/m.meta.resolution),y=Math.floor((xy[1]-m.meta.origin_y)/m.meta.resolution);assert(m.nav.values[y*m.meta.width+x]<0);}assert(Math.hypot(...m.toPlan(...m.toMap(2.425,3.625)).map((v,i)=>v-[2.425,3.625][i]))<1e-9);});
const asset=read('data/assets/robot/mechdog02_visual.json');
check('22 metre-scaled parts; exact stock envelope and measured lidar height',()=>{assert.equal(asset.parts.length,22);const vertices=asset.parts.filter(p=>!['payload_mount','camera_housing','lidar_housing'].includes(p.name)).flatMap(p=>p.vertices);for(let k=0;k<3;k++){const size=Math.max(...vertices.map(v=>v[k]))-Math.min(...vertices.map(v=>v[k]));assert(Math.abs(size-[.214,.126,.138][k])<1e-6);}assert.equal(asset.sensor_mount.lidar_xyz_m[2],.225);assert.equal(asset.body_to_lidar_xy_verified,false);});
const state=(x,yaw,ts,status='valid',mode='offline_test')=>({mode,scene_revision:'test',pose:{visible:true,status,x_m:x,y_m:0,yaw_rad:yaw,source_kind:'unit'},source:{source_timestamp_ms:ts},freshness:{source_age_ms:0}});
check('10Hz position interpolates on intermediate display frames',()=>{const motion=createMotion();motion.ingest(state(0,0,0),0);motion.ingest(state(.1,0,100),100);assert(Math.abs(motion.update(170).x_m-.05)<1e-9);assert(Math.abs(motion.update(200).x_m-.08)<1e-9);});
check('yaw crosses ±pi on the short arc; teleport is immediate and never gait speed',()=>{const motion=createMotion();motion.ingest(state(0,3.12,0),0);motion.ingest(state(.01,-3.12,100),100);const p=motion.update(170);assert(Math.abs(p.yaw_rad-Math.PI)<1e-6);motion.ingest(state(2,0,200),200);const q=motion.update(200);assert.equal(q.x_m,2);assert.equal(q.speed,0);assert.equal(q.blend,0);});
check('lost/recorded stops motion immediately; stationary pose settles to rest',()=>{const motion=createMotion();motion.ingest(state(0,0,0),0);motion.update(0);motion.ingest(state(.02,0,100),100);motion.update(180);assert(motion.update(200).walking);motion.ingest(state(.02,0,200,'lost'),200);const q=motion.update(216,false);assert.equal(q.blend,0);assert.equal(q.x_m,.02);motion.ingest(state(1,0,300,'recorded_candidate','recorded'),300);assert.equal(motion.update(300,false).walking,false);});
check('trot diagonal pairing; feet stay above floor; stationary footstep on yaw',()=>{const motion={phase:Math.PI/2,blend:1,forward:0,turn:1},feet=gaitFeet(motion);assert.equal(feet[0].lift,feet[3].lift);assert(feet[0].lift>0&&feet[1].lift===0&&feet[2].lift===0);const rest=gaitFeet({...motion,blend:0});assert(rest.every(f=>f.lift===0));for(let phase=0;phase<Math.PI*2;phase+=.05)for(const f of gaitFeet({...motion,phase})){const p=legPose(f);assert([p.upperAngle,p.lowerAngle,...p.knee].every(Number.isFinite));assert(f.z>=.008);}});
check('rest IK matches the standing geometry; linked joints remain continuous',()=>{for(const f of gaitFeet({phase:0,blend:0,forward:0,turn:0})){const p=legPose(f);assert(Math.abs(p.upperAngle)<1e-8);assert(Math.abs(p.lowerAngle)<1e-8);assert(Math.hypot(p.knee[0]-p.restKnee[0],p.knee[1]-p.restKnee[1])<1e-8);}});
let tick=1000000;const store=createPoseStore(()=>scene.revision,()=>tick,()=>tick),packet={x_m:1,y_m:2,yaw_rad:0,lost:false,ts_ms:tick,demo:true};
check('production pose parser: invalid/duplicate rejected, stale and lost retain last fix',()=>{assert.equal(store.snapshot().pose.visible,false);assert(store.accept(packet,'unit'));assert.equal(store.accept(packet,'unit'),false);assert.equal(store.accept({...packet,ts_ms:tick+1,x_m:NaN},'unit'),false);tick+=600;assert.equal(store.snapshot().pose.status,'stale');assert.equal(store.snapshot().pose.x_m,1);tick+=100;assert(store.accept({...packet,ts_ms:tick,lost:true,x_m:5},'unit'));assert.equal(store.snapshot().pose.x_m,1);});
const url='http://127.0.0.1:8790',get=async p=>(await fetch(url+p)).json(),post=async(p,v)=>{const r=await fetch(url+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)});return {status:r.status,value:await r.json()};};
const service=await get('/api/status');assert.equal(service.input,'demo');assert.equal(service.revision,scene.revision);
assert.equal((await post('/api/demo/pose',{...packet,ts_ms:Date.now(),demo:false})).status,403);
assert.equal((await post('/api/save',{expected_revision:'wrong',objects:[]})).status,409);
assert.equal((await post('/api/robot/command',{})).status,404);
const wall=scene.objects.find(o=>!o.editable);assert.equal((await post('/api/save',{expected_revision:scene.revision,objects:[{id:wall.id,position:[1,1,0],yaw:wall.yaw,visible:wall.visible}]})).status,400);
for(const p of ['/robot-motion.mjs','/main.js','/presentation.js','/assets/robot/mechdog02_visual.json'])assert.equal((await fetch(url+p)).status,200);
checks.push({name:'isolated HTTP assets, sensor inputs disabled, command API absent, save guards intact',passed:true});
console.log(JSON.stringify({static_checks:checks.length,route:collisions,stream:'70 second 10Hz S0–B–A + stop + turn beginning'},null,2));
const observed=[];let observing=true;
const observation=(async()=>{while(observing){const s=await get('/api/robot/state');observed.push({at:Date.now(),status:s.pose.status,x_m:s.pose.x_m,y_m:s.pose.y_m,yaw_rad:s.pose.yaw_rad,demo:s.demo,accepted:s.counts.accepted});await new Promise(r=>setTimeout(r,100));}})();
const acceptedBefore=(await get('/api/robot/state')).counts.accepted;let demo;
try{demo=await runDemo({seconds:70});}finally{observing=false;await observation;}
write('out/demo_observed.json',observed);
const endState=await get('/api/robot/state'),validObservations=observed.filter(s=>s.status==='valid'&&s.demo).length;
assert(demo.count>=650);assert(observed.length>=300);assert(validObservations/observed.length>.95);assert.equal(endState.counts.accepted-acceptedBefore,demo.count+1);assert.equal(endState.pose.status,'lost');
checks.push({name:'real isolated HTTP 10Hz stream completes route, rest and yaw turn, ends lost',passed:true,packets:demo.count});
for(const p of originalHashes)assert.equal(hash(path.join(originalRoot,p.name)),p.sha256);
checks.push({name:'all selected original 8789 implementation/data bytes unchanged',passed:true});
write('out/verification_T.json',{created_at:new Date().toISOString(),checks,collisions,stream:{transport:'HTTP 8790 only',packets:demo.count,accepted_packets:endState.counts.accepted-acceptedBefore,observed:observed.length,valid_observations:validObservations,observed_hz:observed.length/70,commands_sent:0,sensor_ports_accessed:[]},browser:{verified:false,fps:null,reason:'Browser security policy: user declined localhost 8790 access; no workaround attempted',handoff:'Claude: 1080p plan/follow/eye capture after >=120 frames in visible tab'},original_hashes:originalHashes,risks:scene.realism.limits});
write('out/demo_observed.json',observed);console.log(JSON.stringify({passed:checks.length,packets:demo.count,route_hits:collisions.hits.length,fps:null},null,2));
