import {createPoseStore} from './pose-state.mjs';
﻿import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {spawn} from 'node:child_process';import dgram from 'node:dgram';import {ROOT,read,write,mapData} from './unify.mjs';
const checks=[],check=(name,fn)=>{fn();checks.push({name,passed:true});},url='http://127.0.0.1:8789',pause=ms=>new Promise(r=>setTimeout(r,ms));
const scene=read('data/scene.json'),source=read('data/source_scene.json'),migration=read('out/migration.json'),baseline=read('data/baseline.json');
check('Astra/Claude source hashes unchanged',()=>{for(const p of migration.provenance)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(p.path)).digest('hex'),p.sha256);});
check('13 user-edited furniture transforms preserved',()=>{const edited=migration.audit.filter(a=>a.protected_fields?.length);assert.equal(edited.length,13);for(const a of edited){const o=scene.objects.find(o=>o.id===a.id),old=source.objects.find(o=>o.id===a.id);for(const field of ['position','yaw','visible'])assert.deepEqual(o[field],old[field]);}});
check('22 robot parts and valid canonical mesh indices',()=>{assert.equal(read('data/assets/robot/mechdog02_visual.json').parts.length,22);for(const o of scene.objects)for(const p of o.parts)for(const t of p.triangles)assert(t.length===3&&t.every(i=>Number.isInteger(i)&&i>=0&&i<p.vertices.length));});
check('4 Claude LOD envelopes equal retained metric geometry',()=>{assert.equal(migration.lod_imports.length,4);const bounds=ps=>Array.from({length:3},(_,k)=>[Math.min(...ps.flatMap(p=>p.vertices.map(v=>v[k]))),Math.max(...ps.flatMap(p=>p.vertices.map(v=>v[k])))]);for(const o of scene.objects.filter(o=>o.lod_parts)){const a=bounds(o.parts),b=bounds(o.lod_parts);for(let k=0;k<3;k++)for(let j=0;j<2;j++)assert(Math.abs(a[k][j]-b[k][j])<1e-6);}});
check('wall fit preserves door coherence and wall tangent',()=>{const a=migration.audit.find(a=>a.id==='wall_bedroom_south');assert(Math.abs(a.proposed_shift_m[0])<1e-9);const n=scene.objects.find(o=>o.id==='opening_bedroom_door'),old=source.objects.find(o=>o.id===n.id);assert(Math.abs((n.position[1]-old.position[1])-a.proposed_shift_m[1])<1e-9);});
const map=mapData();check('map transforms round-trip; demo uses observed free cells',()=>{const plan=map.toPlan(2.4,-.5);assert(Math.abs(plan[0]-2.425)<1e-9&&Math.abs(plan[1]-3.625)<1e-9);assert(Math.hypot(...map.toMap(...plan).map((v,k)=>v-[2.4,-.5][k]))<1e-9);for(const p of read('data/demo_route.json').route){const xy=map.toMap(...p),x=Math.floor((xy[0]-map.meta.origin_x)/map.meta.resolution+.00001),y=Math.floor((xy[1]-map.meta.origin_y)/map.meta.resolution+.00001);assert(map.nav.values[y*map.meta.width+x]<0);}});

let tick=1000000;const store=createPoseStore(()=>scene.revision,()=>tick,()=>tick),packet={x_m:4.85,y_m:3.82,yaw_rad:Math.PI,lost:false,moving:true,ts_ms:tick,demo:true};
check('no fabricated initial robot; first lost stays invisible',()=>{assert.equal(store.snapshot().pose.visible,false);store.accept({...packet,lost:true},'unit');assert.equal(store.snapshot().pose.visible,false);});
check('pose_out schema, exact coordinates, moving, demo label',()=>{tick+=100;assert(store.accept({...packet,ts_ms:tick},'unit'));const v=store.snapshot();assert.equal(v.pose.status,'valid');assert.equal(v.pose.x_m,4.85);assert.equal(v.mode,'offline_test');assert.equal(v.moving,true);assert.equal(v.commands_enabled,false);});
check('duplicate/nonfinite/future/stale ingress rejected',()=>{assert.equal(store.accept({...packet,ts_ms:tick},'unit'),false);assert.equal(store.accept({...packet,x_m:Infinity,ts_ms:tick+1},'unit'),false);assert.equal(store.accept({...packet,ts_ms:tick+500},'unit'),false);assert.equal(store.accept({...packet,ts_ms:tick-6000},'unit'),false);});
check('lost keeps last good fix; 500 ms silence becomes stale',()=>{tick+=100;store.accept({...packet,x_m:9,lost:true,ts_ms:tick},'unit');assert.equal(store.snapshot().pose.status,'lost');assert.equal(store.snapshot().pose.x_m,4.85);tick+=100;store.accept({...packet,ts_ms:tick},'unit');tick+=550;assert.equal(store.snapshot().pose.status,'stale');assert.equal(store.snapshot().pose.visible,true);});
check('teleport splits trail; changing source clears old fix',()=>{tick+=100;store.accept({...packet,x_m:1.8,ts_ms:tick},'unit');assert(store.snapshot().trail.at(-1).break_before);tick+=100;store.accept({...packet,lost:true,ts_ms:tick,demo:false},'different');assert.equal(store.snapshot().pose.visible,false);});
check('30 pose samples at 10 Hz simulated acquisition clock',()=>{store.clear();const route=read('data/demo_route.json').route;for(let i=0;i<30;i++){tick+=100;const p=route[Math.floor(i/29*(route.length-1))];assert(store.accept({...packet,x_m:p[0],y_m:p[1],ts_ms:tick},'unit'));}assert.equal(store.snapshot().pose.status,'valid');});
let child;try{
 child=spawn(process.execPath,['server.mjs','--input','off'],{cwd:ROOT,windowsHide:true,stdio:['ignore','pipe','pipe']});let logs='';child.stdout.on('data',c=>logs+=c);child.stderr.on('data',c=>logs+=c);
 let ready=false;for(let i=0;i<40;i++){if(child.exitCode!==null)throw Error(logs);try{const r=await fetch(url+'/api/status');if(r.ok){const v=await r.json();assert.equal(v.input,'off');ready=true;break;}}catch{}await pause(100);}assert(ready,'server ready');
 const get=async p=>(await fetch(url+p)).json(),post=async(p,v)=>{const r=await fetch(url+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)});return{status:r.status,data:await r.json()};};
 assert.equal((await get('/api/robot/state')).pose.visible,false);const status=await get('/api/status');assert.equal(status.revision,scene.revision);assert.equal(status.revision,status.usd_revision);assert.equal((await post('/api/save',{expected_revision:'wrong',objects:[]})).status,409);
 const wall=scene.objects.find(o=>!o.editable);assert.equal((await post('/api/save',{expected_revision:scene.revision,objects:[{id:wall.id,position:[1,1,0],yaw:wall.yaw,visible:wall.visible}]})).status,400);
 const first=scene.objects.find(o=>o.editable),edits=[{id:first.id,position:first.position,yaw:first.yaw,visible:first.visible}];const saved=await post('/api/save',{expected_revision:scene.revision,objects:edits});assert.equal(saved.status,200);assert.equal(saved.data.revision,scene.revision);const exported=await post('/api/export',{});assert.equal(exported.status,200);assert.equal(exported.data.url,'/exports/house_sim.usda');checks.push({name:'HTTP save conflict, locked wall, no-op save/export',passed:true});
 for(const asset of ['/main.js','/presentation.js','/vendor/three.module.js','/assets/robot/mechdog02_visual.json','/comparison.html'])assert.equal((await fetch(url+asset)).status,200);
 assert.equal((await fetch(url+'/api/robot/command',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,404);assert.equal((await fetch(url+'/api/routes')).status,200);checks.push({name:'HTTP assets served; no command API; routes optional',passed:true});
 const usd=fs.readFileSync(path.join(ROOT,'exports/house_sim.usda'),'utf8');assert(usd.startsWith('#usda 1.0'));assert(usd.includes(scene.revision));assert.equal((usd.match(/def Xform "/g)||[]).length,scene.objects.length+1);checks.push({name:'ASCII USD identifiers/revision/mesh structure (no PXR reopen)',passed:true});
 write('out/verification.json',{created_at:new Date().toISOString(),checks,pose_test:{type:'shared production parser/state with simulated clock',packets:30,hz:10,real_transport:false,commands_sent:0},udp_test:{verified:false,port:5399,reason:'bind EACCES 127.0.0.1:5399; no existing listener modified'},geometry:{objects:scene.objects.length,parts:scene.objects.reduce((n,o)=>n+o.parts.length,0),material_batches:scene.objects.reduce((n,o)=>n+new Set(o.parts.map(p=>p.material)).size,0)},browser:{verified:false,reason:'localhost 8789 access denied by browser security policy',screenshots:[],fps:null},isaac:{verified:false,reason:'Python execution denied; PXR/GUI not run'}});console.log(JSON.stringify({passed:checks.length,checks:checks.map(c=>c.name)},null,2));
 }finally{if(child&&child.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}}
